### ISSUE TITLE
Add support for USB webcam

### ISSUE THREAD

**Issue by lelandg** [lelandg/Raspberry-Pi-Security-Camera#19]
In lieu of PiCams. Is this possible? (I think so.) This would simultaneously solve the problem of "one-way-audio". (I.e., right now you can transmit your voice when you're on a video call, but you cannot receive audio. This needs to be a separate issue, BTW.)

**Comment by toshibochan** [comment]
I find the solution! I be post soon!

**Comment by toshibochan** [comment]
If you use USB camera on the python file on the audio and video you have to add to receive video from the camera, mic from the camera and speaker I use 3.5 jack from the pi. But because pi is set audio to go to HDMI you have to set to force to go to 3.5 jack on terminal.

**Comment by lelandg** [comment]
This is now working for the video camera, and it still uses the RaspiCam for the still pictures. Nifty. :)

Closing this issue.
